# Generated by Django 4.0 on 2021-12-16 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceBook',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('attend_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='taughtcourses',
            old_name='id',
            new_name='subject_id',
        ),
        migrations.CreateModel(
            name='StudentFeedback',
            fields=[
                ('stud_feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('stud_feedback', models.TextField()),
                ('Feedback_reply', models.TextField()),
                ('Created_date', models.DateTimeField(auto_now_add=True)),
                ('Updated_date', models.DateTimeField(auto_now_add=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Leave_Report',
            fields=[
                ('Leave_id', models.AutoField(primary_key=True, serialize=False)),
                ('Date_Of_Leave', models.CharField(max_length=255)),
                ('Reason_For_Leave', models.TextField()),
                ('Status_Of_Leave', models.BooleanField(default=False)),
                ('Created_Date', models.DateTimeField(auto_now_add=True)),
                ('Updated_Date', models.DateTimeField(auto_now_add=True)),
                ('Student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='StaffFeedback',
            fields=[
                ('staff_feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_feedback', models.TextField()),
                ('Feedback_reply', models.TextField()),
                ('Created_date', models.DateTimeField(auto_now_add=True)),
                ('Updated_date', models.DateTimeField(auto_now_add=True)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.thestaff')),
            ],
        ),
        migrations.CreateModel(
            name='Staff_Leave_Report',
            fields=[
                ('Leave_id', models.AutoField(primary_key=True, serialize=False)),
                ('Date_Of_Leave', models.CharField(max_length=255)),
                ('Reason_For_Leave', models.TextField()),
                ('Status_Of_Leave', models.BooleanField(default=False)),
                ('Created_Date', models.DateTimeField(auto_now_add=True)),
                ('Updated_Date', models.DateTimeField(auto_now_add=True)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.thestaff')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceBookReport',
            fields=[
                ('attendancerprt_id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance_status', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('attendance_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.attendancebook')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student_management_app.student')),
            ],
        ),
        migrations.AddField(
            model_name='attendancebook',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student_management_app.taughtcourses'),
        ),
    ]
